services:
    mysql_db:
        container_name: laravel-mysql
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            #MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - 3306:3306

    laravel-docker:
        container_name: laravel-docker
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        ports:
            - 8000:8000
        working_dir: /var/www
        depends_on:
            - mysql_db
            - phpmyadmin
#        volumes:
#            - db-data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 9001:80
        environment:
            - PMA_ARBITRARY=1


#
#volumes:
#    db-data: ~
